# -*- coding: utf-8 -*-
"""import_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlEvHJTkZC1YXMQ0dk2Q-Skj-QD0VCvH
"""

def use_module():
  import numpy as np
  import seaborn as sns
  import pandas as pd
  from matplotlib import pyplot as plt
  !pip install japanize-matplotlib
  import japanize_matplotlib

use_module()

